# Generated by Django 6.1 on 2026-08-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_alter_comment_id_alter_contact_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('rate', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
