# Generated by Django 6.1 on 2026-08-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Unknown'),
        ),
    ]
