# Generated by Django 6.1 on 2026-08-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_readership_book_comment_book_language_book_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readership',
            name='email',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='readership',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='readership',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='readership',
            name='gender',
            field=models.CharField(null=True),
        ),
    ]
